<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/bootstrap.rtl.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/aos_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/animate.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/meanmenu_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/remixicon_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/flaticon_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/odometer.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/owl.carousel.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/owl.theme.default.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/jquery-ui.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/magnific-popup.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/fancybox.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/selectize.min_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/style_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/navbar_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/footer_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/dark_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/responsive_2.css') }}">
<link rel="stylesheet" href="{{ asset('layouts/frontend/assets/css/rtl_2.css') }}">
