<script>var hostUrl = "assets/";</script>
<script src="{{ asset('layouts/backend/assets/plugins/global/plugins.bundle.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/js/scripts.bundle.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/plugins/custom/fullcalendar/fullcalendar.bundle.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/index.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/xy.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/percent.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/radar.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/themes/Animated.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/map.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/worldLow.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/continentsLow.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/usaLow.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/worldTimeZonesLow.js') }}"></script>
<script src="https://cdn.amcharts.com/lib/5/geodata/worldTimeZoneAreasLow.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/js/widgets.bundle.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/js/custom/widgets.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/js/custom/utilities/modals/upgrade-plan.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/js/custom/utilities/modals/users-search.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/js/custom/apps/customers/list/export.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/js/custom/apps/chat/chat.js') }}"></script>
<script src="{{ asset('layouts/backend/assets/js/custom/utilities/modals/create-campaign.js') }}"></script>
{{-- <script src="{{ asset('layouts/backend/assets/js/custom/apps/ecommerce/catalog/products.js') }}"></script> --}}
